[project]
name = "transformer-sinhala"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.2.2",
    "datasets>=5.0.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "tensorboard>=2.21.0",
    "tokenizers>=0.23.1",
    "torch>=2.13.0",
    "torchmetrics>=1.9.0",
    "wandb>=0.29.0",
]
